
- name: create catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable old-version and enable New nodejs
    ansible.builtin.shell:  "dnf module disable nodejs -y && dnf module enable nodejs:20 -y"

  - name: install Node js
    ansible.builtin.package: 
      name: nodejs
      state: present

  - name: Adding user with a name of roboshop
    ansible.builtin.user:
      name: roboshop

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: download catalogue application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: exact catalogue application
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: Install npm dependencies
    ansible.builtin.command: npm install
    args: 
      chdir: /app

  - name: copy catalogue . service 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: daemon reload and start
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: copy mongodb repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongodb.repo

  - name: Install mongodb client
    ansible.builtin.package:
      name: mongodb-org
      state: present
  
  - name: Get the categories count
    ansible.builtin.command: mongo --host mongodb.kalyanu.xyz --quiet --eval "db = db.getSiblingDB('catalogue'); db.product.count()"
    register: product_count 

  # - name: print the count
  #   ansible.builtin.debug:
  #     msg: "product count : {{product_count}}"

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.kalyanu.xyz </app/schema/catalogue.js
    when: product_count.stdout == 0

  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: yes