
- name: Creating mysql component
  hosts: mysql
  become: yes
  tasks: 
  - name: Install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Enable mysql
    ansible.builtin.service:
      name: mysqld
      enabled: yes

  - name: Start mysql
    ansible.builtin.service:
      name: mysqld
      state: started

  - name: setup root password
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1