
- name: Creating mysql component
  hosts: mysql
  become: yes
  tasks: 
  - name: Install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: Enable mysql
    ansible.builtin.service:
      name: mysqld
      enabled: yes

  - name: Start mysql
    ansible.builtin.service:
      name: mysqld
      state: started

  - name: Check if MySQL root password is set
    ansible.builtin.shell: mysqladmin -uroot status
    register: mysql_root_status
    ignore_errors: yes

  - name: setup root password
    ansible.builtin.command: mysql -uroot -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';"
    when: mysql_root_status.rc != 0


  # - name: setup root password
    # ansible.builtin.command: mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'RoboShop@1';"


    # mysql_secure_installation --set-root-pass RoboShop@1