

- name: Installing rabbitmq server
  hosts: rabbitmq
  become: yes

  tasks:
    - name: Enable EPEL repo
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Install required dependencies
      ansible.builtin.yum:
        name:
          - socat
          - logrotate
          - erlang
        state: present

    - name: Add RabbitMQ GPG key
      ansible.builtin.rpm_key:
        key: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
        state: present

    - name: Install RabbitMQ server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: present

    - name: Start and enable RabbitMQ
      ansible.builtin.service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Add RabbitMQ user
      ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
      ignore_errors: yes

    - name: Set RabbitMQ user tags
      ansible.builtin.command: rabbitmqctl set_user_tags roboshop administrator
      ignore_errors: yes

    - name: Set permissions for roboshop user
      ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
      ignore_errors: yes
