- name: Installing rabbitmq server
  hosts: rabbitmq
  become: yes

  tasks:

  - name: Enable EPEL repo
    ansible.builtin.yum:
      name: epel-release
      state: present

  - name: Install required dependencies
    ansible.builtin.yum:
      name:
        - socat
        - logrotate
        - erlang
      state: present

  - name: Add RabbitMQ repo (compatible with EL8)
    ansible.builtin.get_url:
      url: https://packagecloud.io/rabbitmq/rabbitmq-server/packages/el/8/rabbitmq-server-3.8.16-1.el8.noarch.rpm/download.rpm
      dest: /tmp/rabbitmq-server.rpm

  - name: Install RabbitMQ manually
    ansible.builtin.yum:
      name: /tmp/rabbitmq-server.rpm
      state: present

  - name: Enable and start RabbitMQ
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: Enable RabbitMQ management UI
    ansible.builtin.command: rabbitmq-plugins enable rabbitmq_management
    register: plugin_output
    changed_when: "'enabled' in plugin_output.stdout"

  - name: Create RabbitMQ user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123
    args:
      creates: /var/lib/rabbitmq/.user_created

  - name: Set RabbitMQ user tags
    ansible.builtin.command: rabbitmqctl set_user_tags roboshop administrator

  - name: Set RabbitMQ permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"
