
- name: Installing rabbitmq server
  hosts: rabbitmq
  become: yes
  tasks: 
  - name: copy rabbitmq . service 
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: Install rabbitmq 
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: Enable rabbitmq 
    ansible.builtin.package:
      name: rabbitmq-server
      enabled: yes 

  - name: Start rabbitmq 
    ansible.builtin.package:
      name: rabbitmq-server
      state: present 

  - name: create rabbitmq user
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: set permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"   