- name: Setup Shipping Component
  hosts: shipping
  become: yes
  vars:
    mysql_host: mysql.kalyanu.xyz
    mysql_password: RoboShop@1
  tasks:
  - name: Install Maven (includes Java)
    ansible.builtin.package:
      name: maven
      state: present

  - name: Create roboshop system user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      system: yes
      comment: roboshop system user
      home: /app

  - name: Remove /app directory if exists
    ansible.builtin.file:
      path: /app
      state: absent

  - name: Create /app directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: Download shipping application
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: Extract shipping app
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: Build Java application using Maven
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: Rename shipping JAR
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: Reload systemd daemon
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable and start shipping service
    ansible.builtin.service:
      name: shipping
      enabled: yes
      state: started

  - name: Install MySQL client
    ansible.builtin.package:
      name: mysql
      state: present

  - name: Load DB Schema
    ansible.builtin.shell: mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} < /app/db/schema.sql
    args:
      executable: /bin/bash

  - name: Create DB app user
    ansible.builtin.shell: mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} < /app/db/app-user.sql
    args:
      executable: /bin/bash

  - name: Load master data
    ansible.builtin.shell: mysql -h {{ mysql_host }} -uroot -p{{ mysql_password }} < /app/db/master-data.sql
    args:
      executable: /bin/bash

  - name: Restart shipping service after DB setup
    ansible.builtin.service:
      name: shipping
      state: restarted
